name: CI/CD Tienda Perritos - Frontend ECS

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/**"

jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build imagen Frontend
        run: |
          cd frontend
          docker build -t tienda-frontend .

      - name: Tag imagen
        run: |
          docker tag tienda-frontend:latest ${{ secrets.ECR_REPO_URL_FRONT }}:latest

      - name: Push imagen a ECR
        run: |
          docker push ${{ secrets.ECR_REPO_URL_FRONT }}:latest

      - name: Desplegar Frontend en ECS
        run: |
          aws ecs update-service \
            --cluster tienda-perrito-cluster \
            --service Frontend-task-service \
            --force-new-deployment